# Generated by Django 4.1.5 on 2023-02-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JKeys', '0002_alter_id_created_alter_id_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
    ]
